import { WidgetDefinition } from '../../../types/dashboard';

export const WIDGET_CATALOG: WidgetDefinition[] = [
  {
    type: 'quick-stats',
    title: 'Quick Stats',
    description: 'Overview of key metrics and statistics',
    icon: 'BarChart3',
    defaultSize: 'small',
    allowedSizes: ['small', 'medium'],
  },
  {
    type: 'tasks-list',
    title: 'Tasks',
    description: 'Upcoming and pending tasks',
    icon: 'CheckSquare',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
  },
  {
    type: 'expenses-summary',
    title: 'Expenses',
    description: 'Recent expenses and spending summary',
    icon: 'DollarSign',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
  },
  {
    type: 'calendar-events',
    title: 'Calendars',
    description: 'Upcoming events and meetings',
    icon: 'Calendar',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
  },
  {
    type: 'staff-status',
    title: 'Staff Status',
    description: 'Who is currently clocked in',
    icon: 'Users',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
  },
  {
    type: 'recent-messages',
    title: 'Messages',
    description: 'Recent conversations and notifications',
    icon: 'MessageSquare',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
  },
  {
    type: 'leave-requests',
    title: 'Leave Requests',
    description: 'Pending leave approval requests',
    icon: 'FileText',
    defaultSize: 'small',
    allowedSizes: ['small', 'medium'],
  },
  {
    type: 'expense-chart',
    title: 'Expense Trends',
    description: 'Visual chart of expense patterns',
    icon: 'TrendingUp',
    defaultSize: 'large',
    allowedSizes: ['medium', 'large'],
  },
  {
    type: 'quick-actions',
    title: 'Quick Actions',
    description: 'Frequently used action buttons',
    icon: 'Zap',
    defaultSize: 'small',
    allowedSizes: ['small', 'medium'],
  },
  {
    type: 'announcements',
    title: 'Announcements',
    description: 'Important system announcements',
    icon: 'Bell',
    defaultSize: 'medium',
    allowedSizes: ['small', 'medium', 'large'],
  },
];
